### ISSUE TITLE
keepassxc plugin stopped working

### ISSUE THREAD

**Issue by kaedechi** [abextm/keepassxc-runelite#14]
have been using the plugin for 6 months ~ without issues but today when i tried to log in i got this issue
already checked  that keepassxc browser integration and other settings are still on 

023-02-03 04:37:07 [KeePassXCSocketConnection] WARN  abex.os.keepassxc.KeePassXcPanel - error connecting to KeePassXC
abex.os.keepassxc.proto.KeePassException: KeePassXC association failed, try again(8)
	at abex.os.keepassxc.proto.KeePassException.create(KeePassException.java:25)
	at abex.os.keepassxc.proto.KeePassXCSocket.call(KeePassXCSocket.java:200)
	at abex.os.keepassxc.proto.KeePassXCSocket.ensureAssociate(KeePassXCSocket.java:260)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:137)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:63)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by LlemonDuck** [comment]
This message indicates that the authorization with the database failed, not the connection. You can try closing the client and deleting ~/.runelite/keepassxc.keyring, as well as disassociating the client in KeePassXC via Database -> Database Settings -> Browser Integration, selecting the entry in Stored Keys, and remove. Then restart the client and it should prompt for reauthorization.

**Comment by kaedechi** [comment]
deleting ~/.runelite/keepassxc.keyring fixed the issue
