### ISSUE TITLE
Issues connecting to Keepass after copying over .runelite folder to new computer

### ISSUE THREAD

**Issue by leadanymind** [abextm/keepassxc-runelite#16]
Followed the runelite suggestions on copying over settings via USB when transferring the .runelite folder over. However, after settuing up Keepass on my new PC, I'm not able to connect to the database when I open runelite.

Any suggestions? 

I've already made sure that my browser integration settings match those shown in the readme. I tried deleting the keyring file and clearing out the jar file in the plugins folder, but I'm all out of ideas. I'm trying to get it to prompt me to connect to my keepass db like the first time I set it up on the old PC.

Thanks,

**Comment by abextm** [comment]
Close RuneLite, delete `keepassxc.keyring` from your `.runelite`, Go into KeePassXC -> Database -> Database Settings -> Browser Integration -> Delete any Stored keys that are for RuneLite.

If that doesn't help, upload your client.log from `.runelite`

**Comment by leadanymind** [comment]
Didn't have any keys stored in there. I imported this DB via csv file exported from other PC. Shouldn't have any additional fluff. Here is my log

```
`2023-04-12 12:02:09 PDT [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.9.14 (launcher version 2.6.3) starting up, args: none
2023-04-12 12:02:09 PDT [RuneLite] INFO  net.runelite.client.RuneLite - Java VM arguments: -XX:ErrorFile=C:\Users\deama\.runelite\logs\jvm_crash_pid_%p.log -XX:+DisableAttachMechanism -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll,GTIII-OSD64-GL.dll,GTIII-OSD64-VK.dll,GTIII-OSD64.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Dsun.java2d.d3d=true -Dsun.java2d.opengl=false -Drunelite.launcher.version=2.6.3
2023-04-12 12:02:11 PDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2023-04-12 12:02:11 PDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached patched client
2023-04-12 12:02:11 PDT [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 4677428447.102
2023-04-12 12:02:12 PDT [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'main' (sync: false, active: true)
2023-04-12 12:02:12 PDT [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'alt' (sync: false, active: false)
2023-04-12 12:02:12 PDT [RuneLite] INFO  n.r.client.config.ConfigManager - Using profile: main
2023-04-12 12:02:12 PDT [RuneLite] INFO  n.r.client.config.ConfigManager - Profile '$rsprofile' is up to date
2023-04-12 12:02:12 PDT [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "elysiumevents-plugin" version "2.1" commit "8955d05b6bfdaf8a080a4e5a8af0ec500a9b743e"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loot-lookup" version "1.1.7" commit "c2255394d09d81cdf0ece8a487afe635d3afe672"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inventory-setups" version "v1.14.4" commit "84559b70b189396d177114aab07607f50f3b00c2"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.4.8" commit "66a9f3edbe1a4007e01c7c2bf440ea8499ed0782"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "c-engineer-completed" version "1.0.4" commit "1930230fbb1ff86797ac738d1f96505ecb658002"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "camera-points" version "2.3.1" commit "23fd5b3b561df43dcce04961eb157388e97234c7"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "radius-markers" version "1.7" commit "c19eb7514776ada5dc28b622cfb55838b7681754"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "party-panel" version "3.2.4" commit "3a58a2768eab1b561feb15371364ceb415fbd483"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "prop-hunt" version "1.1" commit "767fdfccd180ec0255766dea3e0de5ab9f8943b1"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "weapon-charges-2" version "0.5.1" commit "1503c57d4189faf271a4fefa6d37cdceb67581e0"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inferno-stats" version "2.1.3" commit "04bd867ceda46b37c4c799bc2641deeed5dfa0f8"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bats-locator" version "890cefa0" commit "890cefa0a95a734abc15a6b1f0681276c5c78c4d"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "kph-tracker" version "1.9" commit "5e5a1e6f0a7c22c34cdb6ac7260d6cac8351d2aa"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "party-defence-tracker" version "1.0.4" commit "d931a9184fbaa4ad0085d96b0adcdf8013a20832"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menu-swapper-extended" version "1.8" commit "9a5a9cc3278fd552b948bfc62c2ee1a461f6fde1"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tombs-of-amascut" version "2.3.4" commit "336e94ea7b43d0923d1ee61fde3406898917fe51"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "rsn-hider" version "1.2.3.4.5" commit "c5dc87e0b1b4446cd580f898de45fd52300ec2b4"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "skills-tab-progress-bars" version "1.3.1" commit "f1c4afe2af996ec9824b7b3cad3eb8009652cff4"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-notice-board" version "1.1" commit "40af4de25e32af05a1ce15befd62d4afbe6af696"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.2.6" commit "80c8584741947609db5dd690e8643d5764f181fa"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ba-call-highlight" version "21acfedf" commit "21acfedf90291a6cfc5caf145fd734d347ecadca"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "herbi-afk" version "1.1" commit "0602c71e49a3cda7918135ea60bcfdc6badf65eb"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "thrall-helper" version "1.7" commit "c5842a53e66f086526c92b192db27895e0f0ea7f"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "fight-cave-waves" version "1.2" commit "e8315a9eb364fbc5e689ac3b732c96c5854aa4ef"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "customizable-xp-drops" version "1.7.2.3" commit "7e45d09ad8168cd190942bd4d6aaf1f0ea05e42a"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "collection-log" version "2.3.2" commit "ae82b3fe1fc07305310813407c5fdb0cf1b9d3aa"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "volcanic-mine" version "220db26f" commit "220db26f907e2d98d34a4f969e16a7034fa0d956"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "path-marker" version "1.03" commit "17189c5939b019617e6b80fd0843995636cb0fb5"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "flipping-utilities" version "1.4.1" commit "64e77b64ff14ee8cbc70adff597ae756ce0580c0"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "weapon-animation-replacer" version "3.2.0" commit "9f0ae3dfbcbfcef528393866cb580eeb93c887a1"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "theatre-of-blood-stats" version "1.3.3" commit "51b7fd099f09c38d0e1a930bc243cacebb97e310"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-qol" version "1.1.1" commit "1c2387a35b9135868dc2d8617e6cf6b81cc7d239"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "toa-mistake-tracker" version "1.4" commit "8a1b1d809f204ea9630f3664b43581c4ff75a518"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "annoyance-mute" version "1.8.1" commit "8dd954b4aca19cad8ecbe64064502c6a74d9bc75"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "equipment-inspector" version "1.2" commit "c0018d299bb4a3dd4ef971a72bfdc776a42f0ff8"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-solver" version "1.2" commit "ae05921462c576f0c45ce24ee4bbfc9f631cf1dd"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "zulrah-helper" version "1.4.2" commit "2b36735bbea891b96e6b92d7422f621b62afd665"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "boss-hp-reorder" version "1.0" commit "d0ad9b15e6a629b5f595678a4963e3e53eabd914"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "vm-stability-tracker" version "efcb2c31" commit "efcb2c315ba49a174f82a66d85df66c08e0b3d0e"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "supplies-tracker" version "3.0.1" commit "7109cc6862e60c44cb6556cc932794aee6336dff"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "nylo-death-indicators" version "1.0.6" commit "253d5bec65adf1f8f674406f37eedc48a0a50baf"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ca-timers" version "eb6f627b" commit "eb6f627b88d6179cc0b064a4410ff18d1ecbec9a"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "vm-gasper" version "89dd2e67" commit "89dd2e674eb3911ea01db8ca3498feaaa6f09751"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-light-colors" version "1.3.3" commit "caed95658520d3fe382169c1213adf269e78b502"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-infoboxes" version "d36e667b" commit "d36e667b9941e21d4313397f8245443a8a477d17"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "party-health-status" version "6c9a397f" commit "6c9a397f6898614484413c41df899d18a12f5722"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "pet-info" version "4.1" commit "ed0cb05956cfab0f6f28290bfa1411a45d75c454"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "phoenix-necklace-jingle" version "b77e18a5" commit "b77e18a556b1ea3a3fa5d71368e93286de6342be"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "kitten-tracker" version "1.2" commit "150ad6c7148fe5b1659410a72c765a4b576201ab"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bot-detector" version "1.3.9" commit "5ffabc78ba6329cbf612cb7778257a7c57f33a08"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "discord-death-notifications" version "1307c7d6" commit "1307c7d6dcf55bfc7caa6b59a9db0ab8098f711f"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "better-npc-highlight" version "1.0.1" commit "61c894cc8ee0214920d6bdbaf5750190820a290c"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-mistake-tracker" version "2.2" commit "2cb04fce52aaef1a266c53b9fb4459d3bbfd05ba"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "pvp-performance-tracker" version "1.5.5" commit "4af458eb070350627d11d731315e023a3d8df110"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "player-outline" version "1.0" commit "2effa2c2d2900696679488294cb453af94149d22"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "baplus" version "f6c14927" commit "f6c149278d4d9a8c450b8f71cc36824af474694a"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "cox-additions" version "7b1e5342" commit "7b1e5342c504b21a11de0adb6bcfd0ca33f5d863"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "gauntlet" version "1.0.0" commit "e928b24970bd234aad16c3ec3d9005735b852c08"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "betteroverload" version "1.2" commit "743a3f2439850a643f5c43388713de75aafed6af"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tempoross" version "1.2" commit "af72eacca6df48b132232cb4dd5775b225fa2e5e"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wilderness-multi-lines" version "1.2.0" commit "6a61ff3fc499f86757dd29b75286a302d6c351c7"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "object-hider" version "1.1" commit "38e414ccf7756083fdf88ac912823ad2b1e1c1bb"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-tag-layouts" version "1.4.20" commit "e2d1682ba13a9ea7b1b3b875bb045574a56dba89"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "monster-hp-percentage" version "1.2" commit "95cfedd6395aadfc234ffd508c9dc3958fd8f583"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "hotkeyable-menu-swaps" version "2.0.2" commit "6e57566bd7c7c6202132ee9d3bc98fb647341ca5"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "spawnpredictor" version "1.1.0" commit "6000b5035579b9a4a4ecf2508c53c1117411650d"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "volcanic-mine-pre-reset-notifier" version "c4f6ab02" commit "c4f6ab02c8588f7d07ba994e65421c189f648665"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "impling-saver" version "644a0600" commit "644a0600a2029d25722d8070de96bf71df8317c3"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "vengeance-tracker" version "1.2" commit "78efdd2ef95bd71af05f6130c93fa027a581bda2"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "partyreadycheck" version "2.2" commit "1c26bc8051ed23e6e1835aa8a48cc0c0234a56d9"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "quest-helper" version "3.2.4" commit "cf6865a4bee28a21a70abd505ae63580c326b965"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "visual-metronome" version "1.4.5.1" commit "ecc661cf5b6d375fe1a720e8decab39cb383c8fd"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "loading-lines" version "1.1" commit "b281a045a886ed83842e970a91238821e5f5cae1"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wintertodt-notifications" version "1.0" commit "ba06560d1bfd6475efd148e9aaf720a6d91f70aa"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-light-colors" version "1.0" commit "8a608dfa7459784cce1437f14ea35a79cb4ee1a7"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "the-gauntlet" version "1.4" commit "8d49779176e83fec34cecc5f1d4c6e65921cb59b"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-heatmap" version "1.3" commit "716df968d0f6b72060c2424d248b1b52d3669988"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "twitch-live-loadout" version "1.1.0" commit "586f9f87dd9b55063e8a9899456946912b1558aa"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-light-up" version "1.1" commit "a21d1489eb70567854012506a0d8dd7aabb86cc3"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "godbook" version "1.0.2" commit "62e4b93ad66705c4d900cef1dab85b64aa608914"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "detached-camera" version "1.0" commit "225d9fff38ad0f621754c696ea0e919233458da7"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "inferno-wave-splits" version "5e026535" commit "5e0265350ff0d7420440965cf0b666f2cf4ebcf5"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "set-timer" version "2.0.0" commit "45a47eb32763087006459e43e865975fdace68fe"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "healer-tracker" version "1.1" commit "0504219b061168644990033116f443403153e8c5"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "hunllef-helper" version "1.2.2" commit "c933ba48668eb7dce8942203010fb6e734e1f97d"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "jungle-japes-indicator" version "0b2c6d72" commit "0b2c6d72b021dd16538365f71fe65207c25452ce"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "death-charge-reminder" version "1fce1a1c" commit "1fce1a1caad7678c8a87ed3c73a834e017b7b15f"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "keepassxc" version "1.2.0" commit "c7faf033222463e398056b05173c9b56c2aa7858"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "ba-minigame" version "1.68" commit "ea4a9a767d5b03dc9387b24602cc4086f1d8e641"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-xp-value" version "1.2.1" commit "c9fbd80e39860dee6b4ca1a51cee022e91737309"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-points-overlay" version "178e96a5" commit "178e96a5af1ffa883c26c8524b73b038ab15f976"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "world-cycle" version "e44d3443" commit "e44d3443751e5b7deaec75cd0d7d17452c34e154"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "brush-markers" version "1.3" commit "f3b5e086c35a778a8e40b8cc912c095254ea12f4"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tobqol" version "1.1.2" commit "c732be275611bc40bdde1bbd69525e2fd8b04b1b"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "wasted-bank-space" version "e6d4220c" commit "e6d4220c0340f18fe0173bd0459d55aebd3494b4"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tictac7x-charges" version "v0.2.6" commit "cb2e2c13c7cd8f0a759fa34d4fa4e5a8239fe3f8"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "raid-reloader" version "415a4b71" commit "415a4b71a6f94f9f10345f5c825ab1109bc7cb07"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "tob-hm-timer" version "1.0.2" commit "7fd2248690020eaf64a328e0455eb75ab0ac3380"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "one-click-summer-garden" version "2.2.0" commit "11c0f4d7ed85b058121a4568c94b34bb94399379"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "crab-stun-timers" version "1.1" commit "c9c690705613a55aeb0a40282ed78ddd0ad87c69"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "multicolor-highlights" version "1.0.0" commit "0ad4513c87b28e755ed1717a660bfab93232c439"
2023-04-12 12:02:13 PDT [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "menuhp" version "1.1.4" commit "5c0a89ed876794728e42a710bfde2b79b67ec4c0"
2023-04-12 12:02:14 PDT [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2023-04-12 12:02:16 PDT [pool-3-thread-1] INFO  n.r.client.discord.DiscordService - Discord RPC service is ready with user Ganbu.
2023-04-12 12:02:16 PDT [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6562ms. Uptime: 7424ms
2023-04-12 12:02:16 PDT [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,-1350,411,1004x534,invalid,layout=java.awt.BorderLayout,title=RuneLite,normal,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1004x534,invalid,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@38ce1ab2,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2023-04-12 12:02:16 PDT [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: NVIDIA GeForce RTX 4080/PCIe/SSE2
2023-04-12 12:02:16 PDT [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6.0 NVIDIA 528.24
2023-04-12 12:02:19 PDT [KeePassXCSocketConnection] WARN  abex.os.keepassxc.KeePassXcPanel - error connecting to KeePassXC
abex.os.keepassxc.proto.IOTimeoutException: Hit deadline
	at abex.os.keepassxc.proto.InterruptableInputStream.check(InterruptableInputStream.java:41)
	at abex.os.keepassxc.proto.InterruptableInputStream.read(InterruptableInputStream.java:57)
	at com.google.common.io.LittleEndianDataInputStream.readAndCheckByte(LittleEndianDataInputStream.java:231)
	at com.google.common.io.LittleEndianDataInputStream.readInt(LittleEndianDataInputStream.java:117)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:115)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:67)
	at java.base/java.lang.Thread.run(Unknown Source)
`
```

**Comment by abextm** [comment]
Do the KeePassXC browser extensions work?

**Comment by leadanymind** [comment]
I don't have any installed on this PC. Are those required?

**Comment by abextm** [comment]
I don't think so, but according to your logs KeePassXC isn't responding to any messages, so I would like to confirm that it at least works with it's own browser extension

**Comment by leadanymind** [comment]
I'm not sure how to set that up, do you have a link/guide you can point me to?

**Comment by abextm** [comment]
https://keepassxc.org/docs/KeePassXC_GettingStarted#_setup_browser_integration

**Comment by leadanymind** [comment]
The browser extension does seem to work @abextm

**Comment by leadanymind** [comment]
I opened my pc today and it prompted me to save it, not sure why it's fixed now but it is, so closing this issue.
