### ISSUE TITLE
keepassXC errors

### ISSUE THREAD

**Issue by welshkyle123** [abextm/keepassxc-runelite#17]
"abex.os.keepassxc.proto.KeePassEx..." <-- this is the error runelite gives me

hi guys, sorry if its a simple solution. keepassxc is supposed to pull my passwords from my password file on my destop, but runelite keeps giving me this error. it works fine on my desktop but not on my laptop

any suggestions are appreciated

**Comment by LlemonDuck** [comment]
1. Error is missing info, find the full error in ~/.runelite/client.log
2. You probably just need to turn on browser integration on your laptop's KeePass. It's an application setting not a db file setting.

**Comment by welshkyle123** [comment]
> 1. Error is missing info, find the full error in ~/.runelite/client.log
> 2. You probably just need to turn on browser integration on your laptop's KeePass. It's an application setting not a db file setting.

thank you for replying. i have checked the browser integration, it is definitely on. i think this is the log you would like?--

2023-05-23 00:26:55 BST [RuneLite] INFO  net.runelite.client.RuneLite - RuneLite 1.10.0.7 (launcher version 2.6.4) starting up, args: none
2023-05-23 00:26:56 BST [RuneLite] INFO  net.runelite.client.RuneLite - Java VM arguments: -XX:+DisableAttachMechanism -Drunelite.launcher.blacklistedDlls=RTSSHooks.dll,RTSSHooks64.dll,NahimicOSD.dll,NahimicMSIOSD.dll,Nahimic2OSD.dll,Nahimic2DevProps.dll,k_fps32.dll,k_fps64.dll,SS2DevProps.dll,SS2OSD.dll,GTIII-OSD64-GL.dll,GTIII-OSD64-VK.dll,GTIII-OSD64.dll -Xmx512m -Xss2m -XX:CompileThreshold=1500 -Dsun.java2d.d3d=true -Dsun.java2d.opengl=false -Drunelite.launcher.version=2.6.4 -XX:ErrorFile=C:\Users\kyleh\.runelite\logs\jvm_crash_pid_%p.log
2023-05-23 00:26:57 BST [Preloader] INFO  net.runelite.client.rs.ClientLoader - Using cached vanilla client
2023-05-23 00:26:57 BST [Preloader] WARN  net.runelite.client.rs.ClientLoader - Cached patch hash mismatches, regenerating patch
2023-05-23 00:26:58 BST [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 5032991087.140
2023-05-23 00:26:59 BST [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: false, active: true)
2023-05-23 00:26:59 BST [RuneLite] INFO  n.r.client.config.ConfigManager - Profile 'default' (sync: true, active: false)
2023-05-23 00:26:59 BST [RuneLite] INFO  n.r.client.config.ConfigManager - Using profile: default
2023-05-23 00:26:59 BST [RuneLite] INFO  n.r.client.config.ConfigManager - Loading remote configuration for profile '$rsprofile'
2023-05-23 00:27:00 BST [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2023-05-23 00:27:01 BST [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "resource-packs" version "1.4.8" commit "66a9f3edbe1a4007e01c7c2bf440ea8499ed0782"
2023-05-23 00:27:01 BST [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "bank-tag-layouts" version "1.4.21" commit "d9f3ae70e77ec8fbf3bea63ef8b8824b8e178c86"
2023-05-23 00:27:01 BST [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "keepassxc" version "1.2.0" commit "c7faf033222463e398056b05173c9b56c2aa7858"
2023-05-23 00:27:01 BST [RuneLite] INFO  n.r.c.e.ExternalPluginManager - Loading external plugin "117hd" version "1.2.8" commit "ad721beb2dbbc69aaa7d68b7ba352e9fe94e3cc2"
2023-05-23 00:27:02 BST [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2023-05-23 00:27:03 BST [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7868ms. Uptime: 9279ms
2023-05-23 00:27:04 BST [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using device: NVIDIA GeForce RTX 3080 Laptop GPU/PCIe/SSE2
2023-05-23 00:27:04 BST [Client] INFO  n.r.client.plugins.gpu.GpuPlugin - Using driver: 4.6.0 NVIDIA 531.79
2023-05-23 00:27:10 BST [KeePassXCSocketConnection] WARN  abex.os.keepassxc.KeePassXcPanel - error connecting to KeePassXC
abex.os.keepassxc.proto.KeePassException: KeePassXC association failed, try again(8)
	at abex.os.keepassxc.proto.KeePassException.create(KeePassException.java:25)
	at abex.os.keepassxc.proto.KeePassXCSocket.call(KeePassXCSocket.java:201)
	at abex.os.keepassxc.proto.KeePassXCSocket.ensureAssociate(KeePassXCSocket.java:261)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:138)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:67)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-23 00:27:11 BST [KeePassXCSocketConnection] WARN  abex.os.keepassxc.KeePassXcPanel - error connecting to KeePassXC
abex.os.keepassxc.proto.KeePassException: KeePassXC association failed, try again(8)
	at abex.os.keepassxc.proto.KeePassException.create(KeePassException.java:25)
	at abex.os.keepassxc.proto.KeePassXCSocket.call(KeePassXCSocket.java:201)
	at abex.os.keepassxc.proto.KeePassXCSocket.ensureAssociate(KeePassXCSocket.java:261)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:138)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:67)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-23 00:59:35 BST [KeePassXCSocketConnection] WARN  abex.os.keepassxc.KeePassXcPanel - error connecting to KeePassXC
abex.os.keepassxc.proto.KeePassException: KeePassXC association failed, try again(8)
	at abex.os.keepassxc.proto.KeePassException.create(KeePassException.java:25)
	at abex.os.keepassxc.proto.KeePassXCSocket.call(KeePassXCSocket.java:201)
	at abex.os.keepassxc.proto.KeePassXCSocket.ensureAssociate(KeePassXCSocket.java:261)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:138)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:67)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-23 00:59:36 BST [KeePassXCSocketConnection] WARN  abex.os.keepassxc.KeePassXcPanel - error connecting to KeePassXC
abex.os.keepassxc.proto.KeePassException: KeePassXC association failed, try again(8)
	at abex.os.keepassxc.proto.KeePassException.create(KeePassException.java:25)
	at abex.os.keepassxc.proto.KeePassXCSocket.call(KeePassXCSocket.java:201)
	at abex.os.keepassxc.proto.KeePassXCSocket.ensureAssociate(KeePassXCSocket.java:261)
	at abex.os.keepassxc.proto.KeePassXCSocket.init(KeePassXCSocket.java:138)
	at abex.os.keepassxc.KeePassXcPanel.lambda$load$2(KeePassXcPanel.java:67)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by LlemonDuck** [comment]
Try closing RL, deleting the keyring file in your.runelite directory, and restarting RL.

**Comment by welshkyle123** [comment]
> Try closing RL, deleting the keyring file in your.runelite directory, and restarting RL.

thank you! you're awesome. it works now
